# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-03-08 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('sectors', models.CharField(choices=[(b'TECH', b'Technology'), (b'FIN', b'Finance'), (b'CONS', b'Consumer')], max_length=20)),
                ('category', models.CharField(choices=[(b'PUBLIC', b'Public'), (b'PRIVATE', b'Private')], max_length=20)),
                ('total_share', models.FloatField()),
                ('shareholders_equity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeline', models.DateTimeField()),
                ('ltp', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='Company.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_name', models.CharField(max_length=255)),
                ('eps_annual', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarter_reports', to='Company.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Yearly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeline', models.DateTimeField()),
                ('npat', models.FloatField()),
                ('operating_profit', models.FloatField()),
                ('income_tax', models.FloatField()),
                ('interest', models.FloatField()),
                ('long_term_debt', models.FloatField()),
                ('short_term_debt', models.FloatField()),
                ('cash_and_cash_eq', models.FloatField()),
                ('eps', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_reports', to='Company.Company')),
            ],
        ),
    ]
