# Generated by Django 4.0 on 2023-03-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('N', 'N'), ('Z', 'Z')], max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='sectors',
            field=models.CharField(choices=[('Bank', 'Bank'), ('Cement', 'Cement'), ('Ceramics', 'Ceramics'), ('Corporate Bond', 'Corporate Bond'), ('Engineering', 'Engineering'), ('Financial Institusions', 'Financial Institusions'), ('Food and Allied', 'Food and Allied'), ('Fuel and Power', 'Fuel and Power'), ('Insurance', 'Insurance'), ('IT', 'IT'), ('Jute', 'Jute'), ('Life Insurance', 'Life Insurance'), ('Miscellaneous', 'Miscellaneous'), ('Mutual Funds', 'Mutual Funds'), ('Paper and Printing', 'Paper and Printing'), ('Pharmaceuticals and Chemicals', 'Pharmaceuticals and Chemicals'), ('Services and Real Estate', 'Services and Real Estate'), ('Tannery Industries', 'Tannery Industries'), ('Telecommunication', 'Telecommunication'), ('Textile', 'Textile'), ('Travel and Leisure', 'Travel and Leisure')], max_length=70),
        ),
    ]
